<?php

namespace Core\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDataRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserDataRepository extends EntityRepository
{
}
