<?php

namespace Core\AdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRatingRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AdRatingRepository extends EntityRepository
{
}
