node:
    resource: "@NodeBundle/Resources/config/routing.yml"
    prefix:   /

notification:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

ad:
    resource: "@AdBundle/Resources/config/routing.yml"
    prefix:   /

core_message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"